# TOP_SRCDIR must be relative
SRCDIR=..

TARGET = msp430
CONFIG = Debug

all:
	$(MAKE) -f "$(SRCDIR)/Makefile" SRCDIR="$(SRCDIR)" CONFIG="$(CONFIG)" TARGET="$(TARGET)" all

clean:
	$(MAKE) -f "$(SRCDIR)/Makefile" SRCDIR="$(SRCDIR)" CONFIG="$(CONFIG)" TARGET="$(TARGET)" clean
